### ISSUE TITLE
HTML homework, spaces-cr6, Nat Carter

### ISSUE THREAD

**Issue by ghost** [ga-wdi-lessons/html-intro#10]
Comfort: 4.5 / 5
Completeness: 5 / 5

### Three things I learned

1. There is a distinction between the host and the server: The _host_ is the computer on which website files are stored, whereas the _server_ is the piece of software on the host which _serves_ files to the user's browser when those files are requested. (Question: Does _client_ simply mean _user's browser_?)
2. HTML is for semantics; CSS is for style. Ideal HTML does not make any reference to style. (Question: Doesn't Bootstrap completely ignore this principle?)
3. [BrowserStack](https://www.browserstack.com) can be used to test for browser compatibility.

**Comment by amaseda** [comment]
:+1:

1. Yup, client = browser! At least 99% of the time, since the browser is what processes front-end code. But there are technically other ways you (or a program) could do that.

2. Yes, Bootstrap does ignore lots of what would be considered common design principles. Which particular ones are you referring to though?

**Comment by ghost** [comment]
I have almost no experience with Bootstrap, but my question was coming from a vague memory of a "center" class.
